package ru.enzhine.phw2.backend.repositories

import org.springframework.data.jdbc.repository.query.Query
import org.springframework.data.repository.CrudRepository
import org.springframework.data.repository.query.Param
import org.springframework.stereotype.Repository
import ru.enzhine.phw2.backend.entities.UserEntity
import java.util.*

/**
 * Will be auto generated by Spring :)
 */
@Repository
interface CrudUsersRepository : CrudRepository<UserEntity, Long>{
    @Query("SELECT * FROM \"${UserEntity.TABLE_NAME}\" WHERE name = :name")
    fun findByName(@Param("name") name: String): Optional<UserEntity>
}