package ru.enzhine.phw2.backend.repositories

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.data.jdbc.repository.query.Query
import org.springframework.data.repository.CrudRepository
import org.springframework.data.repository.query.Param
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Repository
import ru.enzhine.phw2.backend.entities.DishEntity
import ru.enzhine.phw2.backend.entities.OrderEntity
import ru.enzhine.phw2.backend.entities.UserEntity
import java.util.*

/**
 * Will be auto generated by Spring :)
 */
@Repository
interface CrudOrdersRepository : CrudRepository<OrderEntity, Long> {

    @Query("SELECT * FROM \"${OrderEntity.TABLE_NAME}\" WHERE user_id = :userId")
    fun findByUserId(userId: Long): Iterable<OrderEntity>
}