package ru.enzhine.phw2.backend.repositories

import org.springframework.data.repository.CrudRepository
import org.springframework.stereotype.Repository
import ru.enzhine.phw2.backend.entities.DishEntity

/**
 * Will be auto generated by Spring :)
 */
@Repository
interface CrudDishesRepository : CrudRepository<DishEntity, Long>