package ru.enzhine.phw2.backend.repositories

import org.springframework.data.repository.CrudRepository
import org.springframework.stereotype.Repository
import ru.enzhine.phw2.backend.entities.CookerEntity

/**
 * Will be auto generated by Spring :)
 */
@Repository
interface CustomCookersRepository : CrudRepository<CookerEntity, Long> {}